import { LibrarySettings, Book } from "@/types";

export const DEFAULT_SETTINGS: LibrarySettings = {
  schoolName: "ห้องสมุดหมวดภาษาไทย โรงเรียนบรรหารแจ่มใสวิทยา ๓",
  studentBorrowDays: 5,
  teacherBorrowDays: 10,
  maxBooksPerPerson: 3,
  finePerDay: 25,
  adminUsername: "thaibj3",
  adminPasscode: "12123",
};

export const BOOK_CATEGORIES = [
  "วรรณคดีและวรรณกรรมไทย",
  "หลักภาษาและการใช้ภาษาไทย",
  "วรรณกรรมเยาวชนและนิยายไทย",
  "กวีนิพนธ์ ร้อยกรอง และฉันทลักษณ์",
  "การอ่าน การเขียน และการพูดเพื่อการสื่อสาร",
  "นิทานพื้นบ้าน วรรณกรรมท้องถิ่น และตำนาน",
  "พจนานุกรมและสารานุกรมภาษาไทย",
  "ภาษา ศิลปวัฒนธรรม และประวัติศาสตร์ไทย",
  "วิทยาศาสตร์และเทคโนโลยี",
  "คณิตศาสตร์",
  "ภาษาต่างประเทศ",
  "สังคมศึกษา ศาสนา และวัฒนธรรม",
  "ความรู้ทั่วไปและการพัฒนาตนเอง",
];

export const TEACHER_DEPARTMENTS = [
  "กลุ่มสาระการเรียนรู้ภาษาไทย",
  "กลุ่มสาระการเรียนรู้วิทยาศาสตร์และเทคโนโลยี",
  "กลุ่มสาระการเรียนรู้คณิตศาสตร์",
  "กลุ่มสาระการเรียนรู้ภาษาต่างประเทศ",
  "กลุ่มสาระการเรียนรู้สังคมศึกษา ศาสนา และวัฒนธรรม",
  "กลุ่มสาระการเรียนรู้สุขศึกษาและพลศึกษา",
  "กลุ่มสาระการเรียนรู้ศิลปะ",
  "กลุ่มสาระการเรียนรู้การงานอาชีพ",
  "งานแนะแนว",
  "ฝ่ายบริหารวิชาการ",
];

export const GRADE_LEVELS = [
  "มัธยมศึกษาปีที่ 1",
  "มัธยมศึกษาปีที่ 2",
  "มัธยมศึกษาปีที่ 3",
  "มัธยมศึกษาปีที่ 4",
  "มัธยมศึกษาปีที่ 5",
  "มัธยมศึกษาปีที่ 6",
];

export const ROOM_NUMBERS = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
];

export const SAMPLE_BOOKS: Book[] = [
  {
    id: "TH-001",
    title: "วรรณคดีไทยฉบับวิเคราะห์: ลิลิตพระลอ และ มัทนะพาธา",
    author: "ศ.ดร. รื่นฤทัย สัจจพันธุ์",
    isbn: "978-616-1234-01-1",
    category: "วรรณคดีและวรรณกรรมไทย",
    coverUrl: "https://images.unsplash.com/photo-1532012164546-f432f2e3edd3?w=600&auto=format&fit=crop&q=80",
    status: "AVAILABLE",
    publishedYear: "2567",
    location: "ตู้ภาษาไทย ชั้น 1 (TH-101)",
    description: "วิเคราะห์คุณค่าทางวรรณศิลป์ ปรัชญา และค่านิยมในวรรณคดีเรื่องเอกของไทยสำหรับนักเรียน ม.ปลาย",
    totalBorrowedCount: 0,
    createdAt: "2026-09-01",
  },
  {
    id: "TH-002",
    title: "บรรทัดฐานภาษาไทย เล่ม ๑-๔: หลักไวยากรณ์และการใช้คำ",
    author: "ราชบัณฑิตยสภา",
    isbn: "978-616-1234-02-8",
    category: "หลักภาษาและการใช้ภาษาไทย",
    coverUrl: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&auto=format&fit=crop&q=80",
    status: "AVAILABLE",
    publishedYear: "2566",
    location: "ตู้ภาษาไทย ชั้น 1 (TH-102)",
    description: "คู่มือมาตรฐานหลักภาษาไทย วากยสัมพันธ์ และการสะกดคำที่ถูกต้องตามแบบแผน",
    totalBorrowedCount: 0,
    createdAt: "2026-09-01",
  },
  {
    id: "TH-003",
    title: "ศิลปะการประพันธ์ร้อยกรองและฉันทลักษณ์ไทย",
    author: "อาจารย์ฐะปะนีย์ นาครทรรพ",
    isbn: "978-616-1234-03-5",
    category: "กวีนิพนธ์ ร้อยกรอง และฉันทลักษณ์",
    coverUrl: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80",
    status: "AVAILABLE",
    publishedYear: "2567",
    location: "ตู้ภาษาไทย ชั้น 2 (TH-201)",
    description: "หลักการแต่งโคลง ฉันท์ กาพย์ กลอน และร่าย พร้อมตัวอย่างกวีนิพนธ์ชั้นครู",
    totalBorrowedCount: 0,
    createdAt: "2026-09-01",
  },
  {
    id: "TH-004",
    title: "รามเกียรติ์ ฉบับร้อยแก้วสมบูรณ์",
    author: "พระบาทสมเด็จพระพุทธยอดฟ้าจุฬาโลกมหาราช",
    isbn: "978-616-1234-04-2",
    category: "วรรณคดีและวรรณกรรมไทย",
    coverUrl: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80",
    status: "AVAILABLE",
    publishedYear: "2565",
    location: "ตู้ภาษาไทย ชั้น 1 (TH-103)",
    description: "มหากาพย์วรรณคดีเอกของไทย เล่าเรื่องราวสงครามระหว่างพระรามและทศกัณฐ์อย่างละเอียด เข้าใจง่าย",
    totalBorrowedCount: 0,
    createdAt: "2026-09-01",
  },
  {
    id: "TH-005",
    title: "ขุนช้างขุนแผน ฉบับเรียนรู้และวิเคราะห์",
    author: "สุนทรภู่ และ กวีรัตนโกสินทร์",
    isbn: "978-616-1234-05-9",
    category: "วรรณคดีและวรรณกรรมไทย",
    coverUrl: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&auto=format&fit=crop&q=80",
    status: "AVAILABLE",
    publishedYear: "2566",
    location: "ตู้ภาษาไทย ชั้น 1 (TH-104)",
    description: "วรรณคดีพื้นบ้านสะท้อนวิถีชีวิต ความเชื่อ ขนบประเพณีไทย พร้อมเชิงอรรถและบทวิเคราะห์",
    totalBorrowedCount: 0,
    createdAt: "2026-09-01",
  }
];
