import { Book, BorrowTransaction, BookWishlist } from '@/types';

export const INITIAL_BOOKS: Book[] = [
  {
    id: 'BK-001',
    title: 'ฟิสิกส์ ม.ปลาย เล่ม 1: การเคลื่อนที่และแรง',
    author: 'รศ.ดร.ประสิทธิ์ สุวรรณรัตน์',
    isbn: '978-616-1234-01-1',
    category: 'วิทยาศาสตร์และเทคโนโลยี',
    coverUrl: 'https://images.unsplash.com/photo-1532012164546-f432f2e3edd3?w=600&auto=format&fit=crop&q=80',
    status: 'BORROWED',
    publishedYear: '2566',
    location: 'ตู้ A ชั้น 1 (A1-04)',
    description: 'ตำราฟิสิกส์พื้นฐานและเข้มข้นสำหรับนักเรียนชั้นมัธยมศึกษาตอนปลาย ครอบคลุมเรื่องเวกเตอร์ การเคลื่อนที่แนวตรง และกฎของนิวตัน',
    totalBorrowedCount: 38,
    createdAt: '2024-01-15',
  },
  {
    id: 'BK-002',
    title: 'แคลคูลัสเบื้องต้นสำหรับมัธยมปลายและอุดมศึกษา',
    author: 'ผศ. สมชาย เกียรติอนันต์',
    isbn: '978-616-1234-02-8',
    category: 'คณิตศาสตร์',
    coverUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    status: 'AVAILABLE',
    publishedYear: '2565',
    location: 'ตู้ B ชั้น 2 (B2-12)',
    description: 'เนื้อหาเกี่ยวกับลิมิต ความต่อเนื่อง อนุพันธ์ และการอินทิเกรต พร้อมแบบฝึกหัดโจทย์ประยุกต์และเฉลยละเอียด',
    totalBorrowedCount: 45,
    createdAt: '2024-01-18',
  },
  {
    id: 'BK-003',
    title: 'หลักภาษาไทยและการใช้ภาษาเพื่อการสื่อสาร',
    author: 'อ. กรรณิการ์ พิริยพาณิชย์',
    isbn: '978-616-1234-03-5',
    category: 'ภาษาไทยและวรรณกรรม',
    coverUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&auto=format&fit=crop&q=80',
    status: 'AVAILABLE',
    publishedYear: '2566',
    location: 'ตู้ C ชั้น 1 (C1-02)',
    description: 'หลักการสะกดคำ ราชาศัพท์ วากยสัมพันธ์ และศิลปะการพูด-การเขียนเรียงความอย่างมีประสิทธิภาพ',
    totalBorrowedCount: 29,
    createdAt: '2024-02-01',
  },
  {
    id: 'BK-004',
    title: 'Essential English Grammar & Idioms in Action',
    author: 'David R. Miller & วราภรณ์ สุขสวัสดิ์',
    isbn: '978-616-1234-04-2',
    category: 'ภาษาต่างประเทศ',
    coverUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    status: 'BORROWED',
    publishedYear: '2566',
    location: 'ตู้ D ชั้น 3 (D3-08)',
    description: 'คู่มือไวยากรณ์ภาษาอังกฤษ สำนวน คำศัพท์เชิงลึกสำหรับเตรียมสอบ TCAS, IELTS และการสื่อสารสากล',
    totalBorrowedCount: 52,
    createdAt: '2024-02-05',
  },
  {
    id: 'BK-005',
    title: 'ประวัติศาสตร์ไทยและพัฒนาการทางสังคม',
    author: 'ดร. ธเนศร์ ภักดีดำรง',
    isbn: '978-616-1234-05-9',
    category: 'สังคมศึกษา ศาสนา และวัฒนธรรม',
    coverUrl: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=600&auto=format&fit=crop&q=80',
    status: 'AVAILABLE',
    publishedYear: '2564',
    location: 'ตู้ E ชั้น 2 (E2-15)',
    description: 'วิเคราะห์การเปลี่ยนแปลงทางเศรษฐกิจ การเมือง และวัฒนธรรมของไทยตั้งแต่สมัยสุโขทัยจนถึงยุคปัจจุบัน',
    totalBorrowedCount: 22,
    createdAt: '2024-02-10',
  },
  {
    id: 'BK-006',
    title: 'เรียนรู้ Python และ Machine Learning ฉบับเริ่มต้น',
    author: 'กิตติศักดิ์ พัฒนพันธุ์',
    isbn: '978-616-1234-06-6',
    category: 'วิทยาศาสตร์และเทคโนโลยี',
    coverUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&auto=format&fit=crop&q=80',
    status: 'BORROWED',
    publishedYear: '2567',
    location: 'ตู้ T ชั้น 1 (T1-01)',
    description: 'การเขียนโปรแกรมด้วยภาษาไพทอนเพื่อสร้างโมเดล Data Science และ AI สำหรับนักเรียนมัธยมและผู้เริ่มต้น',
    totalBorrowedCount: 64,
    createdAt: '2024-03-01',
  },
  {
    id: 'BK-007',
    title: 'ต้นส้มแสนรัก (My Sweet Orange Tree)',
    author: 'โฮเซ่ เมอูโร เด วาสคอนเซลอส (แปลโดย สมบัติ เครืองาม)',
    isbn: '978-616-1234-07-3',
    category: 'วรรณกรรมเยาวชนและนิยาย',
    coverUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80',
    status: 'AVAILABLE',
    publishedYear: '2563',
    location: 'ตู้ N ชั้น 3 (N3-05)',
    description: 'วรรณกรรมเยาวชนคลาสสิกระดับโลก บอกเล่าเรื่องราวความอบอุ่น ความผูกพัน และการเติบโตของเด็กชายเซเซ่',
    totalBorrowedCount: 41,
    createdAt: '2024-03-05',
  },
  {
    id: 'BK-008',
    title: 'ศิลปะการวาดภาพและการออกแบบกราฟิกเบื้องต้น',
    author: 'ชลิตา วรรณศิลป์',
    isbn: '978-616-1234-08-0',
    category: 'ศิลปะ ดนตรี และนาฏศิลป์',
    coverUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&auto=format&fit=crop&q=80',
    status: 'AVAILABLE',
    publishedYear: '2565',
    location: 'ตู้ AR ชั้น 2 (AR2-03)',
    description: 'ทฤษฎีสี องค์ประกอบศิลป์ และการใช้เครื่องมือดิจิทัลสำหรับการสร้างสรรค์ผลงานเชิงทัศนศิลป์',
    totalBorrowedCount: 19,
    createdAt: '2024-03-12',
  },
  {
    id: 'BK-009',
    title: 'วิทยาศาสตร์การกีฬาและโภชนาการสำหรับเยาวชน',
    author: 'นพ. วรวิทย์ เกียรติก้อง',
    isbn: '978-616-1234-09-7',
    category: 'สุขศึกษาและพลศึกษา',
    coverUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
    status: 'AVAILABLE',
    publishedYear: '2566',
    location: 'ตู้ PE ชั้น 1 (PE1-07)',
    description: 'การดูแลสมรรถภาพร่างกาย การสร้างกล้ามเนื้อ และโภชนาการที่ถูกต้องสำหรับนักเรียนและนักกีฬาโรงเรียน',
    totalBorrowedCount: 15,
    createdAt: '2024-03-20',
  }
];

export const INITIAL_TRANSACTIONS: BorrowTransaction[] = [
  {
    id: 'TRX-2024-001',
    bookId: 'BK-001',
    bookTitle: 'ฟิสิกส์ ม.ปลาย เล่ม 1: การเคลื่อนที่และแรง',
    bookCoverUrl: 'https://images.unsplash.com/photo-1532012164546-f432f2e3edd3?w=600&auto=format&fit=crop&q=80',
    bookCategory: 'วิทยาศาสตร์และเทคโนโลยี',
    borrower: {
      type: 'STUDENT',
      name: 'เด็กชายธนภัทร สุขเกษม',
      studentId: '54201',
      grade: 'มัธยมศึกษาปีที่ 4 (ม.4)',
      room: '2',
      phone: '081-234-5678'
    },
    borrowDate: '2026-08-25',
    dueDate: '2026-09-01',
    status: 'OVERDUE',
    notes: 'ยืมเพื่อทำโครงงานวิทยาศาสตร์'
  },
  {
    id: 'TRX-2024-002',
    bookId: 'BK-004',
    bookTitle: 'Essential English Grammar & Idioms in Action',
    bookCoverUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    bookCategory: 'ภาษาต่างประเทศ',
    borrower: {
      type: 'TEACHER',
      name: 'ครูนภาลัย วงศ์วิริยะ',
      department: 'กลุ่มสาระการเรียนรู้ภาษาต่างประเทศ',
      phone: '089-876-5432'
    },
    borrowDate: '2026-08-28',
    dueDate: '2026-09-11',
    status: 'ACTIVE',
    notes: 'ใช้ประกอบการเตรียมแผนการสอนวิชาภาษาอังกฤษเข้มข้น ม.5'
  },
  {
    id: 'TRX-2024-003',
    bookId: 'BK-006',
    bookTitle: 'เรียนรู้ Python และ Machine Learning ฉบับเริ่มต้น',
    bookCoverUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600&auto=format&fit=crop&q=80',
    bookCategory: 'วิทยาศาสตร์และเทคโนโลยี',
    borrower: {
      type: 'STUDENT',
      name: 'นางสาวพิชชาพร แสงอรุณ',
      studentId: '54118',
      grade: 'มัธยมศึกษาปีที่ 5 (ม.5)',
      room: '1',
      phone: '086-555-1234'
    },
    borrowDate: '2026-09-01',
    dueDate: '2026-09-08',
    status: 'ACTIVE',
    notes: 'เตรียมตัวแข่งขันทักษะคอมพิวเตอร์ระดับภาค'
  },
  {
    id: 'TRX-2024-004',
    bookId: 'BK-002',
    bookTitle: 'แคลคูลัสเบื้องต้นสำหรับมัธยมปลายและอุดมศึกษา',
    bookCoverUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&auto=format&fit=crop&q=80',
    bookCategory: 'คณิตศาสตร์',
    borrower: {
      type: 'STUDENT',
      name: 'เด็กชายกานต์ รัตนเมธา',
      studentId: '54309',
      grade: 'มัธยมศึกษาปีที่ 6 (ม.6)',
      room: '4',
      phone: '084-333-8899'
    },
    borrowDate: '2026-08-15',
    dueDate: '2026-08-22',
    returnDate: '2026-08-21',
    status: 'RETURNED',
    notes: 'คืนเรียบร้อย สภาพสมบูรณ์'
  }
];

export const INITIAL_WISHLISTS: BookWishlist[] = [
  {
    id: 'WL-001',
    title: 'Generative AI and Prompt Engineering for High School Educators',
    authorPublisher: 'Dr. Alan Vance / O\'Reilly Media',
    department: 'กลุ่มสาระการเรียนรู้วิทยาศาสตร์และเทคโนโลยี',
    reason: 'ต้องการใช้เป็นแหล่งค้นคว้าและพัฒนาหลักสูตรรายวิชาเพิ่มเติมเรื่องปัญญาประดิษฐ์ (AI) สำหรับนักเรียนระดับมัธยมศึกษาตอนปลาย',
    estimatedPrice: 850,
    quantity: 3,
    teacherName: 'ครูอนุชา กิตติพงศ์',
    teacherPhone: '081-999-3322',
    priority: 'HIGH',
    status: 'PENDING',
    isbn: '978-109-815-234-1',
    createdAt: '2026-08-29'
  },
  {
    id: 'WL-002',
    title: 'ชุดวรรณคดีไทยฉบับการ์ตูนความรู้: รามเกียรติ์ & อิเหนา (Boxset 5 เล่ม)',
    authorPublisher: 'สำนักพิมพ์ห้องเรียน / คณะบรรณาธิการภาษาไทย',
    department: 'กลุ่มสาระการเรียนรู้ภาษาไทย',
    reason: 'เพื่อกระตุ้นให้นักเรียนระดับมัธยมศึกษาตอนต้นสนใจอ่านวรรณคดีไทยมากขึ้น โดยใช้ภาพประกอบและการ์ตูนที่มีคุณค่าเชิงวรรณศิลป์',
    estimatedPrice: 1290,
    quantity: 2,
    teacherName: 'ครูพิมพา สุวรรณฉวี',
    teacherPhone: '085-443-2211',
    priority: 'HIGH',
    status: 'APPROVED',
    librarianNotes: 'จัดสรรงบประมาณพัฒนาห้องสมุดประจำภาคเรียนที่ 1 เรียบร้อย รอการสั่งซื้อ',
    isbn: '978-616-456-789-0',
    createdAt: '2026-08-20'
  },
  {
    id: 'WL-003',
    title: 'Olympic Mathematics for Secondary Students: Theory and Problems',
    authorPublisher: 'Titu Andreescu / Springer',
    department: 'กลุ่มสาระการเรียนรู้คณิตศาสตร์',
    reason: 'ใช้ในการติวนักเรียนตัวแทนศูนย์ สอวน. และแข่งขันคณิตศาสตร์โอลิมปิกระดับชาติ',
    estimatedPrice: 1450,
    quantity: 2,
    teacherName: 'ครูธีรพัฒน์ บุญประเสริฐ',
    teacherPhone: '082-112-9988',
    priority: 'MEDIUM',
    status: 'PENDING',
    createdAt: '2026-09-01'
  },
  {
    id: 'WL-004',
    title: 'ภูมิศาสตร์โลกและการเปลี่ยนแปลงสภาพภูมิอากาศ (Climate Change & Earth)',
    authorPublisher: 'สถาบันภูมิศาสตร์และการศึกษาแห่งชาติ',
    department: 'กลุ่มสาระการเรียนรู้สังคมศึกษา ศาสนา และวัฒนธรรม',
    reason: 'ประกอบการเรียนการสอนเรื่องสิ่งแวดล้อมโลกและข้อตกลงสากลลดก๊าซเรือนกระจก',
    estimatedPrice: 420,
    quantity: 4,
    teacherName: 'ครูศศิธร จงกลรักษ์',
    teacherPhone: '087-654-3210',
    priority: 'NORMAL',
    status: 'ORDERED',
    librarianNotes: 'ออกใบสั่งซื้อเลขที่ PO-67/092 กับตัวแทนจัดจำหน่ายแล้ว คาดว่าจะได้รับหนังสือใน 7 วัน',
    createdAt: '2026-08-10'
  }
];
